---
- name: Create the slurm.conf file
  template: dest={{ SLURM_CONF }} src=slurm.conf.j2
  notify: reload slurm

- hostname:
    name: "{{ slurm_server_name }}"

# start SLURM daemon
- name: 'Start SLURM service'
  become: true
  become_user: slurm
  command: slurmctld
  when: ansible_os_family == "Debian" or ansible_virtualization_type == "docker"

- name: 'Start SLURM service'
  service:
    name: slurmctld
    state: started
    enabled: yes
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat" and ansible_virtualization_type != "docker"
    
- name: Ensure slurmd is not running in front node
  shell: pgrep slurmd && killall slurmd
  ignore_errors: yes

- name: Wait Slurm daemon to be up
  wait_for:
    port: 6817

- name: Reconfigure SLURM
  become: true
  become_user: slurm
  command: scontrol reconfigure

- name: allow the slurm user to acces the slurm logs
  file: path=/tmp/slurmctld.log mode=0644
