---
- name: Create the slurm.conf file
  template: dest={{ SLURM_CONF }} src=slurm.conf.j2
  notify: reload slurm

- hostname:
    name: "{{ slurm_server_name }}"

# start SLURM daemon
- name: Create slurmctld systemd unit file
  template:
    src: "slurmctld.service.j2"
    dest: "/etc/systemd/system/slurmctld.service"

- name: SystemD daemon-reload and enable/start slurmctld service
  systemd:
    state: started
    enabled: yes
    name: slurmctld.service
    daemon_reload: yes

- name: Wait Slurm daemon to be up
  wait_for:
    port: 6817

- name: Reconfigure SLURM
  become: true
  become_user: slurm
  command: scontrol reconfigure

- name: allow the slurm user to acces the slurm logs
  file: path=/tmp/slurmctld.log mode=0644
