---
#SLURM dependences
- name: '[EL] Install epel repo'
  yum: name=epel-release,yum-priorities

- name: '[EL] Add SLURM Repo key'
  rpm_key: state=present key="{{ centos_repo_key }}"

- name: '[EL] Add SLURM Repo'
  get_url: url="{{ centos_6_repo_file }}" dest=/etc/yum.repos.d/slurm.repo
  when: ansible_distribution_major_version == "6"

- name: '[EL] Add SLURM Repo'
  get_url: url="{{ centos_7_repo_file }}" dest=/etc/yum.repos.d/slurm.repo
  when: ansible_distribution_major_version == "7"

- name: '[EL] Install rpm slurm packages (common)'
  yum:
    name:
      - "slurm-{{slurm_version}}"
      - "slurm-devel-{{slurm_version}}"
      - "slurm-munge-{{slurm_version}}"
      - "slurm-openlava-{{slurm_version}}"
      - "slurm-pam_slurm-{{slurm_version}}"
      - "slurm-perlapi-{{slurm_version}}"
      - "slurm-plugins-{{slurm_version}}"
      - "slurm-seff-{{slurm_version}}"
      - "slurm-sjobexit-{{slurm_version}}"
      - "slurm-sjstat-{{slurm_version}}"
      - "slurm-slurmdb-direct-{{slurm_version}}"
      - "slurm-slurmdbd-{{slurm_version}}"
      - "slurm-sql-{{slurm_version}}"
      - "slurm-torque-{{slurm_version}}"
    state: present

- name: '[EL] Disable firewall in CentOS 7'
  service: name=firewalld state=stopped enabled=False
  when: ansible_distribution_major_version == "7"
  ignore_errors: yes
