---
- service: name=firewalld state=stopped
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7
  ignore_errors: yes

- name: Create the slurm.conf file
  template: dest={{ SLURM_CONF }} src=slurm.conf.j2
  notify: reload slurm
  when: inventory_hostname != slurm_server_name 

  # start SLURM daemon
- name: Create slurmd systemd unit file
  template:
    src: "slurmd.service.j2"
    dest: "/etc/systemd/system/slurmd.service"

- name: SystemD daemon-reload and enable/start slurmd service
  systemd:
    state: started
    enabled: yes
    name: slurmd.service
    daemon_reload: yes

- name: Wait Slurm daemon in the front-end to be up
  wait_for:
    host: "{{slurm_server_ip}}"
    port: 6817

- name: Reconfigure SLURM
  command: scontrol reconfigure

- name: allow the slurm user to acces the slurm logs
  file: path=/var/log/slurm/slurmd.log mode=0644
