---
- service: name=firewalld state=stopped
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7
  ignore_errors: yes

- name: Create the slurm.conf file
  template: dest={{ SLURM_CONF }} src=slurm.conf.j2
  notify: reload slurm
  when: inventory_hostname != slurm_server_name 

# start SLURM daemon
- name: Start Slurm Daemon
  command: slurmd

- name: Wait Slurm daemon in the front-end to be up
  wait_for:
    host: "{{slurm_server_ip}}"
    port: 6817

- name: Reconfigure SLURM
  command: scontrol reconfigure

- name: allow the slurm user to acces the slurm logs
  file: path=/tmp/slurmd.log mode=0644
